arch: resnet18
aug: true
batch_size: 256
ckpt: ''
color_dist_s: 1.0
config_file: ''
data: imagenet
dist: dp
dist_address: '127.0.0.1:1234'
eval_freq: 50040
gpu: 0
iters: 50040
log_freq: 100
lr: 1.2
lr_schedule: warmup-anneal
multiplier: 2
name: imagenet-reproduce
node_rank: 0
opt: lars
problem: sim-clr
root: ''
save_freq: 12510
scale_lower: 0.08
seed: -1
sync_bn: true
temperature: 0.1
tmp: false
verbose: true
warmup: 0.1
weight_decay: 1.0e-06
workers: 8
world_size: 1
